version: '3.8'

services:
  amazon-job-monitor:
    build: .
    container_name: amazon-job-monitor-full-stack
    restart: unless-stopped
    
    ports:
      - "8080:8080"
    
    environment:
      - USE_SELENIUM=true
      - POLL_INTERVAL=10
      - LOG_LEVEL=INFO
      - DATABASE_PATH=/app/data/jobs.db
      - NODE_ENV=production
      - PORT=8081
    
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s