version: '3.8'

services:
  amazon-pay-rate-monitor:
    build: .
    container_name: amazon-pay-rate-monitor
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - WORKERS=1
      - USE_PLAYWRIGHT=true
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - amazon-monitor-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amazon-monitor.rule=Host(`amazon-monitor.localhost`)"
      - "traefik.http.services.amazon-monitor.loadbalancer.server.port=8000"

networks:
  amazon-monitor-network:
    driver: bridge

volumes:
  logs:
  data: