version: '3.8'

services:
  # Backend API Service (Amazon.ca Scraper)
  amazon-job-bot:
    build: .
    container_name: amazon-job-bot
    restart: unless-stopped
    
    # Environment variables (override in .env file)
    environment:
      - USE_SELENIUM=true
      - POLL_INTERVAL=10
      - LOG_LEVEL=INFO
      - DATABASE_PATH=/app/data/jobs.db
      - PORT=8080
    
    # Load environment variables from .env file
    env_file:
      - .env
    
    # Persistent volumes
    volumes:
      - bot_data:/app/data
      - bot_logs:/app/logs
    
    # Expose port for external access
    ports:
      - "8080:8080"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 30s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network
    networks:
      - job-monitor-network

# Create named volumes for data persistence
volumes:
  bot_data:
    driver: local
  bot_logs:
    driver: local

# Create custom network for service communication
networks:
  job-monitor-network:
    driver: bridge