version: '3.8'

services:
  # Backend API Service
  amazon-job-bot:
    build: .
    container_name: amazon-job-bot
    restart: unless-stopped
    
    # Environment variables (override in .env file)
    environment:
      - USE_SELENIUM=true
      - POLL_INTERVAL=10
      - LOG_LEVEL=INFO
      - DATABASE_PATH=/app/data/jobs.db
    
    # Load environment variables from .env file
    env_file:
      - .env
    
    # Persistent volumes
    volumes:
      - bot_data:/app/data
      - bot_logs:/app/logs
    
    # Expose port for internal communication
    expose:
      - "8080"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/jobs.db') else 1)"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 30s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network
    networks:
      - job-monitor-network

  # Frontend Service
  job-monitor-frontend:
    build: ./job-monitor-frontend
    container_name: job-monitor-frontend
    restart: unless-stopped
    
    # Expose port 80 to host port 3000
    ports:
      - "3000:80"
    
    # Depends on backend
    depends_on:
      - amazon-job-bot
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    
    # Network
    networks:
      - job-monitor-network

# Create named volumes for data persistence
volumes:
  bot_data:
    driver: local
  bot_logs:
    driver: local

# Create custom network for service communication
networks:
  job-monitor-network:
    driver: bridge